#ifndef GSC_MISC_H
#define GSC_MISC_H

#include "logic/game/perk.h"
#include "logic/game/weapon.h"

#define GSC_PERK_QUICK_REVIVE                   "specialty_quickrevive"
#define GSC_PERK_JUGGERNAUT                     "specialty_armorvest"
#define GSC_PERK_SPEED_COLA                     "specialty_fastreload"
#define GSC_PERK_DOUBLE_TAP                     "specialty_rof"
#define GSC_PERK_STAMINA_PLUS                   "specialty_longersprint"
#define GSC_PERK_MULE_KICK                      "specialty_additionalprimaryweapon"

#define GSC_WEAPON_CYMBAL_MONKEY                "zombie_cymbal_monkey"
#define GSC_WEAPON_BLACK_HOLE                   "zombie_black_hole_bomb"
#define GSC_WEAPON_NESTING_DOLLS                "zombie_nesting_dolls"
#define GSC_WEAPON_QUANTUM_BOMB                 "zombie_quantum_bomb"
#define GSC_WEAPON_M1911                        "m1911_zm"
#define GSC_WEAPON_MUSTANG_AND_SALLY            "m1911_upgraded_zm"
#define GSC_WEAPON_PYTHON                       "python_zm"
#define GSC_WEAPON_COBRA                        "python_upgraded_zm"
#define GSC_WEAPON_CZ75                         "cz75_zm"
#define GSC_WEAPON_CALAMITY                     "cz75_upgraded_zm"
#define GSC_WEAPON_M14                          "m14_zm"
#define GSC_WEAPON_MNESIA                       "m14_upgraded_zm"
#define GSC_WEAPON_M16                          "m16_zm"
#define GSC_WEAPON_SKULLCRUSHER                 "m16_gl_upgraded_zm"
#define GSC_WEAPON_G11                          "g11_lps_zm"
#define GSC_WEAPON_G115_GENERATOR               "g11_lps_upgraded_zm"
#define GSC_WEAPON_FAMAS                        "famas_zm"
#define GSC_WEAPON_G16_GL35                     "famas_upgraded_zm"
#define GSC_WEAPON_AK74U                        "ak74u_zm"
#define GSC_WEAPON_AK74FU2                      "ak74u_upgraded_zm"
#define GSC_WEAPON_MP5K                         "mp5k_zm"
#define GSC_WEAPON_MP115_KOLLIDER               "mp5k_upgraded_zm"
#define GSC_WEAPON_MP40                         "mp40_zm"
#define GSC_WEAPON_THE_AFTERBURNER              "mp40_upgraded_zm"
#define GSC_WEAPON_MPL                          "mpl_zm"
#define GSC_WEAPON_MPL_LF                       "mpl_upgraded_zm"
#define GSC_WEAPON_PM63                         "pm63_zm"
#define GSC_WEAPON_TOKYO_AND_ROSE               "pm63_upgraded_zm"
#define GSC_WEAPON_SPECTRE                      "spectre_zm"
#define GSC_WEAPON_PHANTOM                      "spectre_upgraded_zm"
#define GSC_WEAPON_CZ75_DUAL_WIELD              "cz75dw_zm"
#define GSC_WEAPON_CALAMITY_AND_JAME            "cz75dw_upgraded_zm"
#define GSC_WEAPON_STAKEOUT                     "ithaca_zm"
#define GSC_WEAPON_RAID                         "ithaca_upgraded_zm"
#define GSC_WEAPON_OLYMPIA                      "rottweil72_zm"
#define GSC_WEAPON_HADES                        "rottweil72_upgraded_zm"
#define GSC_WEAPON_SPAS_12                      "spas_zm"
#define GSC_WEAPON_SPAZ_24                      "spas_upgraded_zm"
#define GSC_WEAPON_HS10                         "hs10_zm"
#define GSC_WEAPON_TYPHOID_AND_MARY             "hs10_upgraded_zm"
#define GSC_WEAPON_AUG                          "aug_acog_zm"
#define GSC_WEAPON_AUG_50M3                     "aug_acog_mk_upgraded_zm"
#define GSC_WEAPON_GALIL                        "galil_zm"
#define GSC_WEAPON_LAMENTATION                  "galil_upgraded_zm"
#define GSC_WEAPON_COMMANDO                     "commando_zm"
#define GSC_WEAPON_PREDATOR                     "commando_upgraded_zm"
#define GSC_WEAPON_FN_FAL                       "fnfal_zm"
#define GSC_WEAPON_EPC_WN                       "fnfal_upgraded_zm"
#define GSC_WEAPON_DRAGUNOV                     "dragunov_zm"
#define GSC_WEAPON_D115_DISASSEMBLER            "dragunov_upgraded_zm"
#define GSC_WEAPON_L96A1                        "l96a1_zm"
#define GSC_WEAPON_L115_ISOLATOR                "l96a1_upgraded_zm"
#define GSC_WEAPON_RPK                          "rpk_zm"
#define GSC_WEAPON_R115_RESONATOR               "rpk_upgraded_zm"
#define GSC_WEAPON_HK21                         "hk21_zm"
#define GSC_WEAPON_H115_OSCILATOR               "hk21_upgraded_zm"
#define GSC_WEAPON_M72_LAW                      "m72_law_zm"
#define GSC_WEAPON_M72_ANARCHY                  "m72_law_upgraded_zm"
#define GSC_WEAPON_CHINA_LAKE                   "china_lake_zm"
#define GSC_WEAPON_CHINA_BEACH                  "china_lake_upgraded_zm"
#define GSC_WEAPON_RAY_GUN                      "ray_gun_zm"
#define GSC_WEAPON_PORTERS_X2_RAY_GUN           "ray_gun_upgraded_zm"
#define GSC_WEAPON_THUNDERGUN                   "thundergun_zm"
#define GSC_WEAPON_ZEUSCANNON                   "thundergun_upgraded_zm"
#define GSC_WEAPON_CROSSBOW                     "crossbow_explosive_zm"
#define GSC_WEAPON_AWFUL_LAWTON                 "crossbow_explosive_upgraded_zm"
#define GSC_WEAPON_BALLISTIC_KNIFE              "knife_ballistic_zm"
#define GSC_WEAPON_KRAUSS_REFIBRILLATOR         "knife_ballistic_upgraded_zm"
#define GSC_WEAPON_BALLISTIC_KNIFE_BOWIE        "knife_ballistic_bowie_zm"
#define GSC_WEAPON_KRAUSS_REFIBRILLATOR_BOWIE   "knife_ballistic_bowie_upgraded_zm"

const char* gscGetPerkName(Perk perk);
const char* gscGetWeaponName(Weapon weapon);

#endif // GSC_MISC_H