#include "logic/cheat/manager/registry.h"

const CheatDefinition CHEAT_REGISTRY[] = {
    // HacksConfig
    { CHEAT_NAME_GOD_MODE,            CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_NO_CLIP,             CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_INVISIBLE,           CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_INFINITE_AMMO,       CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_INSTANT_KILL,        CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_NO_RECOIL,           CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_SMALL_CROSSHAIR,     CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_FAST_GAMEPLAY,       CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_NO_SHELLSHOCK,       CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_INCREASE_KNIFE_RANGE,CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_BOX_NEVER_MOVES,     CHEAT_COND_GAME_ONGOING },
    { CHEAT_NAME_THIRD_PERSON,        CHEAT_COND_GAME_ONGOING },
    // GraphicsConfig
    { CHEAT_NAME_MAKE_BORDERLESS,     CHEAT_COND_NONE },
    { CHEAT_NAME_UNLIMIT_FPS,         CHEAT_COND_NONE },
    { CHEAT_NAME_DISABLE_HUD,         CHEAT_COND_NONE },
    { CHEAT_NAME_DISABLE_FOG,         CHEAT_COND_NONE },
    { CHEAT_NAME_FULLBRIGHT,          CHEAT_COND_NONE },
    { CHEAT_NAME_COLORIZED,           CHEAT_COND_NONE },
    // GameConfig
    { CHEAT_NAME_FIX_MOVEMENT_SPEED,  CHEAT_COND_NONE },
    { CHEAT_NAME_SHOW_FPS,            CHEAT_COND_NONE },
};
const int NUM_CHEAT_REGISTRY = sizeof(CHEAT_REGISTRY) / sizeof(CHEAT_REGISTRY[0]);

const SimpleCheatDefinition SIMPLE_CHEAT_REGISTRY[] = {
    { SIMPLE_CHEAT_NAME_CHANGE_NAME,                        CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_SET_HEALTH,                         CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_SET_POINTS,                         CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_SET_SPEED,                          CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_SET_KILLS,                          CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_SET_HEADSHOTS,                      CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_CHANGE_HOSTNAME,                    CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_FOV,                                CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_FOV_SCALE,                          CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_FPS_CAP,                            CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_GIVE_WEAPON,                        CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_GIVE_AMMO,                          CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_TELEPORT,                           CHEAT_COND_GAME_ONGOING },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_SCORE_BACKGROUND,        CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_SCORE_P1,                CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_SCORE_P2,                CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_SCORE_P3,                CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_SCORE_P4,                CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_TRANSPARENCY_POINTS,     CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_TRANSPARENCY_SCOREBOARD, CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_RELOAD_PRIMARY,     CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_RELOAD_SECONDARY,   CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_LOW_AMMO_PRIMARY,   CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_LOW_AMMO_SECONDARY, CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_NO_AMMO_PRIMARY,    CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_NO_AMMO_SECONDARY,  CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_FREQUENCY,          CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_MIN,                CHEAT_COND_NONE },
    { SIMPLE_CHEAT_NAME_CUSTOMIZER_WARN_MAX,                CHEAT_COND_NONE },
};
const int NUM_SIMPLE_CHEAT_REGISTRY = sizeof(SIMPLE_CHEAT_REGISTRY) / sizeof(SIMPLE_CHEAT_REGISTRY[0]);

const CheatDefinition* findCheatDefinition(CheatName cheat) {
    for (int i = 0; i < NUM_CHEAT_REGISTRY; i++) {
        if (CHEAT_REGISTRY[i].name == cheat) {
            return &CHEAT_REGISTRY[i];
        }
    }
    return NULL;
}

const SimpleCheatDefinition* findSimpleCheatDefinition(SimpleCheatName cheat) {
    for (int i = 0; i < NUM_SIMPLE_CHEAT_REGISTRY; i++) {
        if (SIMPLE_CHEAT_REGISTRY[i].name == cheat) {
            return &SIMPLE_CHEAT_REGISTRY[i];
        }
    }
    return NULL;
}

bool isManagedToggleCheat(CheatName cheat) {
    return findCheatDefinition(cheat) != NULL;
}
