#include "cheat.h"

// Cheats Offsets
#define CHEAT_OFFSET_GOD_MODE 0x01A79868
#define CHEAT_OFFSET_INVISIBLE CHEAT_OFFSET_GOD_MODE
#define CHEAT_OFFSET_NO_CLIP 0x01C0A74C
#define CHEAT_OFFSET_NO_RECOIL 0x006562F0
#define CHEAT_OFFSET_FAST_GAMEPLAY 0x0248173C
#define CHEAT_OFFSET_NO_SHELLSHOCK 0x02F67C5C
#define CHEAT_OFFSET_INCREASE_KNIFE_RANGE 0x00BCAFE4
#define CHEAT_OFFSET_BOX_NEVER_MOVES 0x026210F4
#define CHEAT_OFFSET_THIRD_PERSON 0x026210F0
#define CHEAT_OFFSET_SMALL_CROSSHAIR 0x00BDF31C
#define CHEAT_OFFSET_INVALID 0x00000000

// Cheats Values
#define CHEAT_VALUE_GOD_MODE_ON 2081
#define CHEAT_VALUE_GOD_MODE_OFF 2080
#define CHEAT_VALUE_INVISIBLE_ON 2085
#define CHEAT_VALUE_NO_CLIP_ON 1
#define CHEAT_VALUE_NO_CLIP_OFF 0
#define CHEAT_VALUE_NO_RECOIL_ON 117
#define CHEAT_VALUE_NO_RECOIL_OFF 116
#define CHEAT_VALUE_FAST_GAMEPLAY_ON 2.0f
#define CHEAT_VALUE_FAST_GAMEPLAY_OFF 1.0f
#define CHEAT_VALUE_NO_SHELLSHOCK_ON 0
#define CHEAT_VALUE_NO_SHELLSHOCK_OFF 1
#define CHEAT_VALUE_INCREASE_KNIFE_RANGE_ON 2000.0f
#define CHEAT_VALUE_INCREASE_KNIFE_RANGE_OFF 64.0f
#define CHEAT_VALUE_BOX_NEVER_MOVES_ON 50759716
#define CHEAT_VALUE_BOX_NEVER_MOVES_OFF 50759780
#define CHEAT_VALUE_THIRD_PERSON_ON 1
#define CHEAT_VALUE_THIRD_PERSON_OFF 0
#define CHEAT_VALUE_SMALL_CROSSHAIR_ON 0.009999999776f
#define CHEAT_VALUE_SMALL_CROSSHAIR_OFF 0.6499999762f
#define CHEAT_VALUE_INVALID 0

// Cheats Asm Instructions Addresses
#define CHEAT_ASM_OFFSET_INFINITE_AMMO 0x00697A10 // Address where the Infinite Ammo assembly instruction is located.
#define CHEAT_ASM_OFFSET_SMALL_CROSSHAIR 0x00406DEA
#define CHEAT_ASM_OFFSET_INSTANT_KILL 0x007CE731
#define CHEAT_ASM_OFFSET_INVALID 0x00000000

// Cheats Asm Instruction Sets
#define CHEAT_ASM_INFINITE_AMMO_INSTRUCTION_SET_ON { 0x90, 0x90, 0x90 } // nop; nop; nop
#define CHEAT_ASM_INFINITE_AMMO_INSTRUCTION_SET_OFF { 0x89, 0x50, 0x04 } // mov [eax+04], edx
#define CHEAT_ASM_INFINITE_AMMO_INSTRUCTION_SET_ON_SIZE 3
#define CHEAT_ASM_INFINITE_AMMO_INSTRUCTION_SET_OFF_SIZE 3
#define CHEAT_ASM_SMALL_CROSSHAIR_INSTRUCTION_SET_ON { 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90 } // nop; nop; nop; nop; nop; nop; nop; nop; nop; nop;
#define CHEAT_ASM_SMALL_CROSSHAIR_INSTRUCTION_SET_OFF { 0xF7, 0x83, 0xFC, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0C } // test dword ptr [ebx+4FC], 0C000000h
#define CHEAT_ASM_SMALL_CROSSHAIR_INSTRUCTION_SET_ON_SIZE 10
#define CHEAT_ASM_SMALL_CROSSHAIR_INSTRUCTION_SET_OFF_SIZE 10
#define CHEAT_ASM_INSTANT_KILL_INSTRUCTION_SET_ON { 0xC7, 0x80, 0x84, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } // mov [eax+184], 0
#define CHEAT_ASM_INSTANT_KILL_INSTRUCTION_SET_OFF { 0x29, 0x98, 0x84, 0x01, 0x00, 0x00 } // sub [eax+184], ebx
#define CHEAT_ASM_INSTANT_KILL_INSTRUCTION_SET_ON_SIZE 10
#define CHEAT_ASM_INSTANT_KILL_INSTRUCTION_SET_OFF_SIZE 6


Cheat CHEAT_GOD_MODE = {
    CHEAT_OFFSET_GOD_MODE,
    {.u32 = CHEAT_VALUE_GOD_MODE_ON},
    {.u32 = CHEAT_VALUE_GOD_MODE_OFF},
};

Cheat CHEAT_INVISIBLE = {
    CHEAT_OFFSET_INVISIBLE,
    {.u32 = CHEAT_VALUE_INVISIBLE_ON},
    {.u32 = CHEAT_VALUE_INVALID},
};

Cheat CHEAT_NO_CLIP = {
    CHEAT_OFFSET_NO_CLIP,
    {.byte = CHEAT_VALUE_NO_CLIP_ON},
    {.byte = CHEAT_VALUE_NO_CLIP_OFF},
};

Cheat CHEAT_NO_RECOIL = {
    CHEAT_OFFSET_NO_RECOIL,
    {.byte = CHEAT_VALUE_NO_RECOIL_ON},
    {.byte = CHEAT_VALUE_NO_RECOIL_OFF},
};

Cheat CHEAT_FAST_GAMEPLAY = {
    CHEAT_OFFSET_FAST_GAMEPLAY,
    {.f32 = CHEAT_VALUE_FAST_GAMEPLAY_ON},
    {.f32 = CHEAT_VALUE_FAST_GAMEPLAY_OFF},
};

Cheat CHEAT_NO_SHELLSHOCK = {
    CHEAT_OFFSET_NO_SHELLSHOCK,
    {.byte = CHEAT_VALUE_NO_SHELLSHOCK_ON},
    {.byte = CHEAT_VALUE_NO_SHELLSHOCK_OFF},
};

Cheat CHEAT_INCREASE_KNIFE_RANGE = {
    CHEAT_OFFSET_INCREASE_KNIFE_RANGE,
    {.f32 = CHEAT_VALUE_INCREASE_KNIFE_RANGE_ON},
    {.f32 = CHEAT_VALUE_INCREASE_KNIFE_RANGE_OFF},
};

Cheat CHEAT_BOX_NEVER_MOVES = {
    CHEAT_OFFSET_BOX_NEVER_MOVES,
    {.u32 = CHEAT_VALUE_BOX_NEVER_MOVES_ON},
    {.u32 = CHEAT_VALUE_BOX_NEVER_MOVES_OFF},
};

Cheat CHEAT_THIRD_PERSON = {
    CHEAT_OFFSET_THIRD_PERSON,
    {.byte = CHEAT_VALUE_THIRD_PERSON_ON},
    {.byte = CHEAT_VALUE_THIRD_PERSON_OFF},
};

Cheat CHEAT_SMALL_CROSSHAIR = {
    CHEAT_OFFSET_SMALL_CROSSHAIR,
    {.f32 = CHEAT_VALUE_SMALL_CROSSHAIR_ON},
    {.f32 = CHEAT_VALUE_SMALL_CROSSHAIR_OFF},
};

CheatAsm CHEAT_ASM_INFINITE_AMMO = {
    CHEAT_ASM_OFFSET_INFINITE_AMMO,
    {CHEAT_ASM_INFINITE_AMMO_INSTRUCTION_SET_ON, CHEAT_ASM_INFINITE_AMMO_INSTRUCTION_SET_ON_SIZE}, 
    {CHEAT_ASM_INFINITE_AMMO_INSTRUCTION_SET_OFF, CHEAT_ASM_INFINITE_AMMO_INSTRUCTION_SET_OFF_SIZE},
};

CheatAsm CHEAT_ASM_SMALL_CROSSHAIR = {
    CHEAT_ASM_OFFSET_SMALL_CROSSHAIR,
    {CHEAT_ASM_SMALL_CROSSHAIR_INSTRUCTION_SET_ON, CHEAT_ASM_SMALL_CROSSHAIR_INSTRUCTION_SET_ON_SIZE}, 
    {CHEAT_ASM_SMALL_CROSSHAIR_INSTRUCTION_SET_OFF, CHEAT_ASM_SMALL_CROSSHAIR_INSTRUCTION_SET_OFF_SIZE},
};

CheatAsm CHEAT_ASM_INSTANT_KILL = {
    CHEAT_ASM_OFFSET_INSTANT_KILL,
    {CHEAT_ASM_INSTANT_KILL_INSTRUCTION_SET_ON, CHEAT_ASM_INSTANT_KILL_INSTRUCTION_SET_ON_SIZE}, 
    {CHEAT_ASM_INSTANT_KILL_INSTRUCTION_SET_OFF, CHEAT_ASM_INSTANT_KILL_INSTRUCTION_SET_OFF_SIZE},
};
